okayish

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -36,25 +36,21 @@ jobs:
           gut_params: -gdir=res://tests/unit
           project_path: src
 
-  checks:
-    runs-on: ubuntu-latest
+      - name: Check resources
+        run: |
+          CHANGES=$(git status --porcelain | grep -E '\.res$|\.tres$' || true)
 
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
+          echo "Changed files:"
+          echo "$CHANGES"
 
-      - name: Checkout LFS objects
-        run: git lfs pull
+          if [[ -n "$CHANGES" ]]; then
+            echo "::error::Some .tres or .res files are not up to date. Please run the Resource Resaver (button in the top-right of the Godot Editor) and fix any broken resources!"
+            git diff -- '*.res' '*.tres'
+            exit 1
+          else
+            echo "All resources are up to date"
+          fi
 
-      - name: unit tests with godot gut
-        uses: 100-Devs-1-Game/godot-gut-ci@feature/add-resource-check
-        with:
-          godot_version: ${{ env.GODOT_VERSION }}
-          gut_params: -gdir=res://tests/unit
-          project_path: src
-
-      - name: Status
-        run: git status
 
 # echo git status:
 # echo "$(git status --porcelain)"
